apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo
---
## Annotations & Labels
apiVersion: v1
kind: Pod
metadata:
  name: pod03
  annotations:
    training/class: devops
  labels:
    type: test
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod04
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: termination-demo
spec:
  containers:
  - name: termination-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "sleep 10 && echo Sleep expired > /dev/termination-log"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - name: volme
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "while true ;do  date >/data/out; sleep 1; done"]
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: pod05
spec:
  enableServiceLinks: false
  containers:
    - name: nginx
      image: nginx
