apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo
---
## Annotations & Labels
apiVersion: v1
kind: Pod
metadata:
  name: pod03
  annotations:
    training/class: devops
  labels:
    type: test
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod04
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
