apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

 ---
apiVersion: v1
kind: Service
metadata:
  name: my-service-nginx
  labels:
   app.kubernetes.io/name: MyApp
spec:
 containers:
   - name: nginx
     image: nginx

