apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    appname: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    appname: MyApp
spec:
 containers:
   - name: nginx
     image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-1
spec:
  type: NodePort 
  selector:
    appname: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80